### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by thomaseizinger** [Xaeroxe/async-io-typed#1]
Hi!

Thanks for making this! I came across it through TWIR and couldn't help myself but spot the similarity to `asynchronous-codec`: https://github.com/mxinden/asynchronous-codec (which itself is a fork of the unmaintained `futures-codec`).

It is less opinionated but you could consider implementing your message format as a codec instead! :)

**Comment by Xaeroxe** [comment]
Thanks for alerting me to this! I'll evaluate the various `*-codec` crates and see what makes sense for the future of this project.

**Comment by thomaseizinger** [comment]
You are welcome. Personally, I am quite fond of the `Encoder` and `Decoder` abstraction as they tend to compose very well.

**Comment by Xaeroxe** [comment]
In order to do this I would need to sacrifice a feature from this crate, `stream_end`, because it's not possible for a codec to send bytes without an item being provided. The ability to explicitly end the stream is useful because it enables you to terminate the connection even on I/O channels which don't support being closed or disconnected normally. At least one implementation was found in use that doesn't support normal termination.

Additionally, these traits don't seem to provide any more composability than this crate already supports. Both approaches would *consume* an `AsyncRead` or `AsyncWrite`.

**Comment by thomaseizinger** [comment]
> Additionally, these traits don't seem to provide any more composability than this crate already supports. Both approaches would _consume_ an `AsyncRead` or `AsyncWrite`.

The `Encoder` and `Decoder` traits are not meant to be used directly but rather through the `Framed` abstraction which provides `Stream` and `Sink` implementations for a stream, based on the codec, i.e. `stream.next()` will yield a fully decoded message.

> In order to do this I would need to sacrifice a feature from this crate, `stream_end`, because it's not possible for a codec to send bytes without an item being provided.

Does `stream_end` send a message to the other side? If so, then IMO the way to model that would be to have an `Encoder` that accepts directly this message to be sent.

You can always build another "stream" abstraction on top that internally uses `Framed` to send the individual messages if you don't want the expose the control messages of your protocol to the end user.
